#!/usr/bin/env zsh
function dvenv() {
set -u
if [[ -f "${HOME}/.virtualenvs/default/bin/activate" ]]; then
  source "${HOME}/.virtualenvs/default/bin/activate"
else
  echo "${HOME}/.virtualenvs/default/bin/activate could not be found!"
fi
set +u
}

function avenv() {
set -u
if [[ -f "${HOME}/.virtualenvs/ansible/bin/activate" ]]; then
  source "${HOME}/.virtualenvs/ansible/bin/activate"
else
  echo "${HOME}/.virtualenvs/ansible/bin/activate could not be found!"
fi
set +u
}
