name: CI
on:
  push:
    branches: ["main"]
  pull_request: 
    branches: ["main"]
  workflow_dispatch:
jobs:
  deploy:
    strategy:
      matrix:
        role: [base,admin,dev]
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        path: .dotfiles
    - name: Install Vscode
      run: |
        curl -fsSL https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg | sudo gpg --dearmor -o /usr/share/keyrings/codium.gpg
        echo 'deb [ signed-by=/usr/share/keyrings/codium.gpg ] https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs vscodium main' | sudo tee /etc/apt/sources.list.d/codium.list
        sudo chmod 644 /etc/apt/sources.list.d/codium.list
        sudo apt update -y
        sudo apt install -y codium 
      # Tests for vim tmux zsh zsh-syntax-highlighting zsh-autosuggestions missing as of now
    - name: Install dotfiles
      run: ${PWD}/install ${{ matrix.role }}
      working-directory: ${HOME}/.dotfiles
